AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='App')),

]

AXF/App/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^home/$', home, name='home'),

    url(r'^market/$', market, name='market'),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),

    url(r'^mine/$', mine, name='mine'),
    url(r'^register/$', register, name='register'),
    url(r'^registerhandle/$', register_handle, name='register_handle'),
    url(r'^checkusername/$', check_username, name='check_username'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', login, name='login'),
    url(r'^loginhandle/$', login_handle, name='login_handle'),

    url(r'^cart/$', cart, name='cart'),
    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^reducenum/$', reduce_num, name='reduce_num'),
    url(r'^deletecart/$', delete_cart, name='delete_cart'),
    url(r'^cartselect/$', cart_select, name='cart_select'),
    url(r'^cartselectall/$', cart_selectall, name='cart_selectall'),

    url(r'^orderadd/$', order_add, name='order_add'),
    url(r'^order/(\d+)/$', order, name='order'),
    url(r'^orderchangestatus/$', order_change_status, name='order_change_status'),
    url(r'^orderwaitpay/$', order_waitpay, name='order_waitpay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),

]

AXF/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/user/login.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'js/md5.js' %}"></script>
    <script src="{% static 'app/user/login.js' %}"></script>
{% endblock %}


{% block header %}
    <header>
        <div>登录</div>
    </header>
{% endblock %}


{% block content %}

    <div class="container">

        <form method="post" action="{% url 'App:login_handle' %}" >
            {% csrf_token %}

            <div class="form-group">
                <label>用户名</label>
                <input id="username" name="username" type="text" class="form-control"
                       placeholder="请输入用户名"/>
            </div>
            {% if status == 0 %}
                <p style="color: #f34;">{{ msg }}</p>
            {% endif %}

            <div class="form-group">
                <label>密码</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="请输入密码"/>
            </div>

            <button id="login" type="submit" class="btn btn-success">登录</button>
        </form>
    </div>

{% endblock %}

AXF/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/user/register.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'js/md5.js' %}"></script>
    <script src="{% static 'app/user/register.js' %}"></script>
{% endblock %}


{% block header %}
    <header>
        <div>注册</div>
    </header>
{% endblock %}


{% block content %}

    <div class="container">

        <form method="post" action="{% url 'App:register_handle' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label>用户名</label>
                <input id="username" name="username" type="text" class="form-control"
                       placeholder="6-18位的数字字母下划线,不能以数字开头"/>
            </div>
            <p id="msg"></p>

            <div class="form-group">
                <label>密码</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="8位以上字符"/>
            </div>
            <div class="form-group">
                <label>确认密码</label>
                <input id="again" type="password" class="form-control" placeholder="请再次输入密码"/>
            </div>
            <div class="form-group">
                <label>邮箱</label>
                <input id="email" name="email" type="email" class="form-control" placeholder="请输入合法的邮箱"/>
            </div>
            <div class="form-group">
                <label>头像</label>
                <input id="icon" name="icon" type="file"/>
            </div>
            <button id="register" type="submit" class="btn btn-success">注册</button>
        </form>
    </div>

{% endblock %}