AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='App')),

]

AXF/App/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^home/$', home, name='home'),

    url(r'^market/$', market, name='market'),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),

    url(r'^mine/$', mine, name='mine'),
    url(r'^register/$', register, name='register'),
    url(r'^registerhandle/$', register_handle, name='register_handle'),
    url(r'^checkusername/$', check_username, name='check_username'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', login, name='login'),
    url(r'^loginhandle/$', login_handle, name='login_handle'),

    url(r'^cart/$', cart, name='cart'),
    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^reducenum/$', reduce_num, name='reduce_num'),
    url(r'^deletecart/$', delete_cart, name='delete_cart'),
    url(r'^cartselect/$', cart_select, name='cart_select'),
    url(r'^cartselectall/$', cart_selectall, name='cart_selectall'),

    url(r'^orderadd/$', order_add, name='order_add'),
    url(r'^order/(\d+)/$', order, name='order'),
    url(r'^orderchangestatus/$', order_change_status, name='order_change_status'),
    url(r'^orderwaitpay/$', order_waitpay, name='order_waitpay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),

]

AXF/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block content %}
    <div id="mine">

        {# 顶部的个人信息 #}
        <div class="fixed">
            {% if icon %}
                <img src="{% static icon %}">
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}

            {% if name %}
                <a href="#">{{ name }}</a>
            {% else %}
                <a href="{% url 'App:login' %}">登录</a>
            {% endif %}

            <p>
                <span class=" glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

            <div id="regis">
                <a href="{% url 'App:register' %}">注册</a>
            </div>

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                <span>收藏</span>
            </p>

        </div>

        {# 订单信息 #}
        <div class="mine mine2">
            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">
                <ul>
                    <li>
                        <a href="{% url 'App:order_waitpay' %}">
                            <dl>
                                <dt class="glyphicon glyphicon-usd"></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'App:order_paid' %}">
                            <dl>
                                <dt class="glyphicon glyphicon-envelope"></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-pencil"></dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-retweet"></dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-envelope"></dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-credit-card"></dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-import"></dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-phone-alt"></dt>
                            <dd>客户反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt class="glyphicon glyphicon-certificate"></dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>


            {# 退出登录 #}
            {% if name %}
                <p>
                    <a href="{% url 'App:logout' %}">退出</a>
                </p>
            {% endif %}


        </div>



    </div>
{% endblock %}