AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='App')),

]

AXF/App/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^home/$', home, name='home'),

    url(r'^market/$', market, name='market'),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),

    url(r'^mine/$', mine, name='mine'),
    url(r'^register/$', register, name='register'),
    url(r'^registerhandle/$', register_handle, name='register_handle'),
    url(r'^checkusername/$', check_username, name='check_username'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', login, name='login'),
    url(r'^loginhandle/$', login_handle, name='login_handle'),

    url(r'^cart/$', cart, name='cart'),
    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^reducenum/$', reduce_num, name='reduce_num'),
    url(r'^deletecart/$', delete_cart, name='delete_cart'),
    url(r'^cartselect/$', cart_select, name='cart_select'),
    url(r'^cartselectall/$', cart_selectall, name='cart_selectall'),

    url(r'^orderadd/$', order_add, name='order_add'),
    url(r'^order/(\d+)/$', order, name='order'),
    url(r'^orderchangestatus/$', order_change_status, name='order_change_status'),
    url(r'^orderwaitpay/$', order_waitpay, name='order_waitpay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),

]

AXF/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">

    {% block extCSS %}
    {% endblock %}


    <script src="{% static 'js/base.js' %}"></script>


    <title>{% block title %}axf{% endblock %}</title>
</head>
<body>

    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}


    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/swiper.jquery.js' %}"></script>

    {% block extJS %}
    {% endblock %}

</body>
</html>

AXF/templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'App:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'App:market' %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'App:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'App:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}